### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by rjdsq** [ehnait/contactPutianHospital#1]
未能成功部署，失败告终，可否指点一二。
运行后弹出浏览器窗口，一长串网址，显示为：{"status":0,"data":{}}

**Comment by rjdsq** [comment]
vx：peonyking

**Comment by ehnait** [comment]
> 未能成功部署，失败告终，可否指点一二。 运行后弹出浏览器窗口，一长串网址，显示为：{"status":0,"data":{}}

1.  检查config.py文件下浏览器路径是否正确，浏览器可执行文件路径可以在chrome浏览器的地址栏中输入：chrome://version 查看
2.  更新代码到最新版本尝试
3.  如果以上操作还不能解决，尝试运行catch.py更新api.txt

**Comment by wayne2tech** [comment]
大佬，这个还需要设备有gpu吗

**Comment by ehnait** [comment]
> 大佬，这个还需要设备有gpu吗

我不清楚哎 我是用的DrissionPage三方库，我这也有gpu报错...但是不影响运行

**Comment by jb228899** [comment]
![福昕截屏20230819164034286](https://github.com/ehnait/contactPutianHospital/assets/138748171/ece83a8e-5a06-4682-ac6d-9f960491c38c)
这步看不懂啊，能不能线上教教

**Comment by ehnait** [comment]
> ![福昕截屏20230819164034286](https://github.com/ehnait/contactPutianHospital/assets/138748171/ece83a8e-5a06-4682-ac6d-9f960491c38c)
> 
> 这步看不懂啊，能不能线上教教

这个项目不需要安装驱动

**Comment by jb228899** [comment]
有点看不懂，能不能留个方式线上聊

**Comment by ehnait** [comment]
> 有点看不懂，能不能留个方式线上聊
> 
> 

本项目里的README有 使用教程 讲的很清楚了

**Comment by weirdo-pjg** [comment]
> 未能成功部署，失败告终，可否指点一二。 运行后弹出浏览器窗口，一长串网址，显示为：{"status":0,"data":{}}

老哥你解决了吗

**Comment by 731879846kk** [comment]
程序运行了，只成功了一个就一直卡着了

**Comment by ehnait** [comment]
> 

截图说明

**Comment by ehnait** [comment]
> 

#2  
[试试这个](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.1)

**Comment by RWGLQJ** [comment]
> 未能成功部署，失败告终，可否指点一二。 运行后弹出浏览器窗口，一长串网址，显示为：{"status":0,"data":{}}

解决了吗老哥

**Comment by vanbolee** [comment]
一样的问题，自动打开的浏览器网页显示{"status":0,"data":{}}，手动将网址在新开浏览器打开能访问正常

**Comment by weirdo-pjg** [comment]
> 一样的问题，自动打开的浏览器网页显示{"status":0,"data":{}}，手动将网址在新开浏览器打开能访问正常

![image](https://github.com/ehnait/contactPutianHospital/assets/77140158/902e70a4-9745-4f8a-a213-db08fba50a77)
提前打开百度页面，chrome浏览器的问题，也可以改浏览器设置，然后看看楼主新更新的东西

**Comment by vanbolee** [comment]
> 后看看楼主新更新的

哈哈  我目前也是这么处理的，打开浏览器先开个百度首页

**Comment by ehnait** [comment]
> > 一样的问题，自动打开的浏览器网页显示{"status":0,"data":{}}，手动将网址在新开浏览器打开能访问正常
> 
> ![image](https://user-images.githubusercontent.com/77140158/264946105-902e70a4-9745-4f8a-a213-db08fba50a77.png) 提前打开百度页面，chrome浏览器的问题，也可以改浏览器设置，然后看看楼主新更新的东西

 这次总算找到根了🤣

**Comment by vanbolee** [comment]
不过跑了50几个页面，只接到一个电话，感觉此方案仅供学习

**Comment by weirdo-pjg** [comment]
> 不过跑了50几个页面，只接到一个电话，感觉此方案仅供学习

这个不是那种违法的骚扰电话，你可以把无界面关掉看看，只是模拟了咨询网站发送手机号，然后再别人给你回电话那种。技术点在于浏览器模拟操作，不过后遗症挺大，可能今后几天都会有不间断电话打给你哈哈哈
