### ISSUE TITLE
关于无头模式下的运行情况

### ISSUE THREAD

**Issue by kisny** [ehnait/contactPutianHospital#10]
我修改了无头模式为True，然后断点单步走了一下代码，发现好像会找不到元素 。
（我没用过python所以不太熟，这些只是我的猜测）
如果有什么好的测试方法也请告诉我，我来试下，谢谢

**Comment by ehnait** [comment]
修复好了 ，试试

https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.3

**Comment by kisny** [comment]
好的，我试下
