### ISSUE TITLE
抓取的网页class是否未更新?

### ISSUE THREAD

**Issue by ddddict** [ehnait/contactPutianHospital#12]
看了下页面好像已经不存在'@class:pc-icon-leave-tel'了,使用最新代码无效果,换成了这几个标签可以正常运行,通过点击留言按钮,在对话框中填写姓名和手机号再点击提交, 不知道这样是否合理,还是原有代码也可以正常运行?
`icon_leave_tel = tab.ele('@class:pc-icon-leave-message')
        if icon_leave_tel:
            icon_leave_tel.click(by_js=True)
            leavetel_input = tab.ele('@class:tel-input ')
            leavetel_input.input('18888888888')
            name_input = tab.ele('@class:name-input')
            name_input.input('姓名')
            callback = tab.ele('@class:leaveword-submit')
            if callback:
                callback.click(by_js=True)
                tab_title = tab.title`

**Comment by ehnait** [comment]
感谢🫡  !
已修复 #[v0.1.4](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.4)
