### ISSUE TITLE
可否添加点击去官网按钮,并留电获取验证码功能?

### ISSUE THREAD

**Issue by ddddict** [ehnait/contactPutianHospital#13]
在原有基础上新增获取验证码功能

1. 打开url并按流程处理完后, 点击对话框中`去官网`按钮
2. 点击官网页面`极速处理`按钮
3. 在弹框中填写手机号,并点击`获取验证码`按钮
4. 关闭两个页面

**Comment by ehnait** [comment]
已添加 [v0.1.5](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.5)

**Comment by ddddict** [comment]
大佬这个逻辑没太看懂,是要等所有留言结束了再处理官网页面吗, 看浏览器开了一堆官网页面不操作

**Comment by ehnait** [comment]
@ddddict   我做了一点修改 ，加入了注释  , 如果开启了发送验证码  ，就不用多线程处理了
[v0.1.6](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.6)
（我自测同一个手机号不能重复发送）

**Comment by chomry** [comment]
很多时候留言还没提交出来页面就关闭了，也有很多时候页面刚加载就关闭了，但是程序却提示留言成功了，应该没有成功吧？

**Comment by chomry** [comment]
> @ddddict 我做了一点修改 ，加入了注释 , 如果开启了发送验证码 ，就不用多线程处理了 [v0.1.6](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.6) （我自测同一个手机号不能重复发送）

Message: no such element: Unable to locate element: {"method":"css selector","selector":".pc-icon-leave-tel"}

**Comment by ehnait** [comment]
@chomry    对留言成功提示加了条限制   89c331a426502c5f29ff6ab309bfc70116cea331

**Comment by chomry** [comment]
我安装了pandas模块之后就不能正常运行了，提示：
Traceback (most recent call last):
  File "D:\Python\putian\main.py", line 115, in <module>
    iterate_api('api.txt')
  File "D:\Python\putian\main.py", line 98, in iterate_api
    urls = file.readlines()
  File "D:\Python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6948: invalid continuation byte

**Comment by chomry** [comment]
我发现每4个页面是一个周期，每打开4个页面只能成功留言第一个，其他3个页面都是秒开秒关闭，这种应该是没留言上吧？页面加载时间能延长一下吗大佬

**Comment by ehnait** [comment]
> 我发现每4个页面是一个周期，每打开4个页面只能成功留言第一个，其他3个页面都是秒开秒关闭，这种应该是没留言上吧？页面加载时间能延长一下吗大佬

是最新的代码吗吗？

**Comment by chomry** [comment]
> > 我发现每4个页面是一个周期，每打开4个页面只能成功留言第一个，其他3个页面都是秒开秒关闭，这种应该是没留言上吧？页面加载时间能延长一下吗大佬
> 
> 是最新的代码吗吗？

是的，你的没有这种情况吗？

**Comment by NiBuLiHai** [comment]
good,加油

**Comment by nanfengyue** [comment]
现在这个短信功能是不是去掉了？代码都注释了，是不能用吗？还是得解开注释？

**Comment by ehnait** [comment]
> 现在这个短信功能是不是去掉了？代码都注释了，是不能用吗？还是得解开注释？

因为现在工作忙，先只保留一个稳定的功能。 短信功能不太稳定，先注释掉了

**Comment by NiBuLiHai** [comment]
不理解你在说什么,可以微信聊:Liu_Ru_Yan_



在 2024-12-18 17:17:58，"tianhe" ***@***.***> 写道：

现在这个短信功能是不是去掉了？代码都注释了，是不能用吗？还是得解开注释？

主要是为了现在工作忙，先只保留一个稳定的功能。
