### ISSUE TITLE
网页元素变动

### ISSUE THREAD

**Issue by Double-H-Github** [ehnait/contactPutianHospital#16]
你好，我发现网页元素变动了，“留电”变成了“留言”，导致程序无法运行了。我尝试自己去修复了一下，但是看起来没有正常运行，大哥能帮忙改一下，push一下吗？我学习一下，感谢

**Comment by ehnait** [comment]
你先更新到最新代码

**Comment by Double-H-Github** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Double-H-Github** [comment]
请教一下你是怎么获取这些百度广告的网址的？

**Comment by ehnait** [comment]
> 请教一下你是怎么获取这些百度广告的网址的？

调用这个脚本   https://github.com/ehnait/contactPutianHospital/blob/main/catchad/catch.py
