### ISSUE TITLE
作者你好，请问聊天内容是否能自定义呢

### ISSUE THREAD

**Issue by ningift** [ehnait/contactPutianHospital#19]
聊天内容千篇一律，接单员很容易察觉是程序回复，是否能做成可自定义留言
![QQ截图20231225142400](https://github.com/ehnait/contactPutianHospital/assets/61674553/3c751888-4419-4f82-8390-31e2c7d6ca12)

**Comment by ehnait** [comment]
这不是我控制的，    是那个网站自己的模版
