### ISSUE TITLE
效率问题

### ISSUE THREAD

**Issue by weirdo-pjg** [ehnait/contactPutianHospital#2]
![image](https://github.com/ehnait/contactPutianHospital/assets/77140158/54def9fc-2ec5-424c-bbd4-16293e6c481a)
楼主的方式只是用线程开了窗口，实际发送消息还是单线程的，所以效率不是很高，我修改了一下，可以多线程创建窗口并发送

**Comment by ehnait** [comment]
感谢反馈~  但是通过while的方式其实也是阻塞了主线程， 这更像是对url列表进行了分割

‘’实际发送消息还是单线程的‘’这是因为我之前用DrissionPage创建多个tab后对其进行模拟点击操作时，发现如果焦点不在当前tab上会导致失败 。所以后才把实际处理的部分放在了new_tab函数外面了。

看了你的反馈后，我又仔细读了一下文档 ，发现在DrissionPage的API中 `ele.click(by_js=True)`可以解决这个问题.

> by_js为True时，则可无视任何遮挡，只要元素在 DOM 内，就能点击得到，可以根据须要灵活地对元素进行操作。

我在commit[0ac492e](https://github.com/ehnait/contactPutianHospital/commit/0ac492efedb8f3f50dd409670c84a6550f511b5b)中修复了这个问题，并提交[v0.1.1](https://github.com/ehnait/contactPutianHospital/releases/tag/v0.1.1)

**Comment by lidachui0809** [comment]
楼主 出现这种情况 有啥方法可以解决吗 
![image](https://github.com/ehnait/contactPutianHospital/assets/95042812/4e6c048d-e47b-4e20-97f7-a6703b26d3d8)

**Comment by ehnait** [comment]
看看这个  https://github.com/ehnait/contactPutianHospital/issues/1

**Comment by ehnait** [comment]
> 楼主 出现这种情况 有啥方法可以解决吗 
> 
> ![image](https://github.com/ehnait/contactPutianHospital/assets/95042812/4e6c048d-e47b-4e20-97f7-a6703b26d3d8)
> 
> 

看看这个  https://github.com/ehnait/contactPutianHospital/issues/1
