### ISSUE TITLE
部分网页打开后不会自动关闭

### ISSUE THREAD

**Issue by fake985** [ehnait/contactPutianHospital#20]
如以下网址，打开后不会自动关闭
https://sjh.baidu.com/site/0532fk.com/ef8a0226-cde2-4272-89f3-1d5299cc7655
https://sjh.baidu.com/site/puji120.cn/e99be3d7-da8a-4b8c-90b1-8460f5b7d831
https://sjh.baidu.com/site/xjydgc120.com/a210a1af-7597-4550-94c3-f1f9ce3b14ec
![QQ截图20231226092415](https://github.com/ehnait/contactPutianHospital/assets/61674553/6154d185-5cd5-4cc2-bd21-fce7d9118ea2)

**Comment by ehnait** [comment]
已修复
此问题导致的原因是，如果打开ENABLE_OTP=True后，由于某一些网址内的元素没有“极速预约”这个按钮所导致查找失败报了个错误，但这不影响后续程序运行。
