### ISSUE TITLE
早上运行还好好的 下午就出问题

### ISSUE THREAD

**Issue by c517273374** [ehnait/contactPutianHospital#3]
连接浏览器失败，可能原因：
1、浏览器未启动
2、9600端口不是Chromium内核浏览器
3、该浏览器未允许控制
4、和已打开的浏览器冲突
请尝试用ChromiumOptions指定别的端口和指定浏览器路径

**Comment by ehnait** [comment]
http://g1879.gitee.io/drissionpagedocs/ChromiumPage/browser_options/#auto_port

把上次启动的浏览器关掉
