### ISSUE TITLE
怎么知道程序是正常运行的

### ISSUE THREAD

**Issue by wyl2000** [ehnait/contactPutianHospital#4]
修改main.py首先要打开百度，所有网页都一闪而过，正常时医院那个页面要点击留下电话号，才有用，这个程序在命令行下只显示成功打开了一个标题为xxxx的医院网站，自己新扫的网站，也是这样，这个可能没有成功留下电话，页面仅仅打开了，没能点击那个留下电话回拔，自动化是失败的。手动留下电话是有用的。但是这个程序感觉没功能没实现

**Comment by JiaoYuanZhou** [comment]
我也遇到这个问题了

**Comment by JiaoYuanZhou** [comment]
[92019:61715:0907/144511.909576:ERROR:sdp_offer_answer.cc(2321)] Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.并且浏览器一直报这个ERROR

**Comment by ehnait** [comment]
> 修改main.py首先要打开百度，所有网页都一闪而过，正常时候医院那个页面要留下点击电话号，适用，这个程序在命令行下只显示成功打开了一个标题为xxxx的医院网站，自己新扫的网站，也是这样，这个可能没有成功留下电话，页面只需打开了，没能点击那个留下电话回拔，自动化是失败的。手动留下电话是有用的。但是这个程序感觉没功能没实现

你可以在 process_tab 函数中的 finally代码块中加入 `  time.sleep(10)`延迟关闭页面

**Comment by ehnait** [comment]
> [92019:61715:0907/144511.909576:ERROR:sdp_offer_answer.cc(2321)] Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.并且浏览器一直报这个ERROR

这个报错不会影响程序的正常运行，你就理解成DrissionPage的一个bug吧。（打开会话页面的时候就会报这个错）

**Comment by JiaoYuanZhou** [comment]
> > [92019:61715:0907/144511.909576:ERROR:sdp_offer_answer.cc(2321)] Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.并且浏览器一直报这个ERROR
> 
> 这个报错不会影响程序的正常运行，你就理解成DrissionPage的一个bug吧。（打开会话页面的时候就会报这个错）

非常感谢您的解答
