### ISSUE TITLE
跑了几次发现是按api.txt里的顺序来的，如果是像callPhoneBoom一样完全随机的从列表里去选的就好了

### ISSUE THREAD

**Issue by 275609505** [ehnait/contactPutianHospital#7]

**Comment by ehnait** [comment]
用函数random.shuffle(urls) 自己洗下牌
![1](https://github.com/ehnait/contactPutianHospital/assets/35953595/a5ab03e0-5128-4938-b6c6-af6eb8b10549)

**Comment by ehnait** [comment]
使用random.shuffle() 函数洗一下

![WeChatacce2fde8cba39764fe95a109ad43f56](https://github.com/ehnait/contactPutianHospital/assets/35953595/2707eba3-0ba9-456b-9bf3-31c693d9a951)

**Comment by 275609505** [comment]
好的，谢谢，另外一个问题是，如果我只知道对方的QQ号码，我怎么修改留给给客服的联系方式的文字说明。

**Comment by 275609505** [comment]
> 使用random.shuffle() 函数洗一下
> 
> ![WeChatacce2fde8cba39764fe95a109ad43f56](https://user-images.githubusercontent.com/35953595/273420454-2707eba3-0ba9-456b-9bf3-31c693d9a951.jpg)

好的，谢谢，另外一个问题是，如果我只知道对方的QQ号码，我怎么修改留给给客服的联系方式的文字说明。

**Comment by 275609505** [comment]
> 使用random.shuffle() 函数洗一下
> 
> ![WeChatacce2fde8cba39764fe95a109ad43f56](https://user-images.githubusercontent.com/35953595/273420454-2707eba3-0ba9-456b-9bf3-31c693d9a951.jpg)

 我没在代码里面找到这个不分，那个文字说明是API里自动提供的吗

**Comment by ehnait** [comment]
@275609505   如果你需要随机顺序，就自己加上`random.shuffle(urls)`   ,  留给给客服的联系方式的文字说明是网站端自己定义的  ，不支持修改
